# Generated by Django 5.1.5 on 2025-02-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksmodel',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('text_review', models.TextField(default='Крутой фильм')),
                ('stars', models.CharField(
                    choices=[('🌟', '🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')],
                    default='🌟🌟🌟', max_length=10)),
                ('choice_book',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_book',
                                   to='books.booksmodel')),
            ],
        ),
    ]
